### ISSUE TITLE
安装提示无效的结构

### ISSUE THREAD

**Issue by MV9KEz7nx6dx** [yfang1644/kodi_plugins#1]
直接下载kodi_plugins_master.zip 安装提示无效的结构 主要的几个插件不能用 优酷 和爱奇艺 可以搜索 但是无法播放 个别插件提示依赖不满足 其中bigmovies的依赖cntv-video 可能打错了 写成cvtn了 还有hdpparser 依赖从哪获得？ 能看美剧足矣 谢谢大神 期待更新

**Comment by yfang1644** [comment]
谢谢你的关注。

直接下载的master.zip 是 github的功能，不负责结构问题。解压后可以得到各个插件的zip文件，可以使用
zip 安装方式逐个安装。
其实只需要下载一个zip文件安装，然后从这个库安装其他插件即可：
https://github.com/yfang1644/kodi_plugins/raw/master/repository.xbmc-chinese-videos/repository.xbmc-chinese-videos-1.0.1.zip
我近期在随时更新。几个插件的搜索功能可能有问题，但多数插件从列表里列出来的是可以看的。
而人人美剧则建议使用搜索功能搜索早期的剧集，因为我没找到全部剧集的接口，自己做了一个
搜索数据库。

我不是大神。多数插件也不是我的原创。bigmovies 片源好像断了。我也没放进我的插件库里。
我定制的插件里没有依赖 hdpparser 的。它可能来自 https://github.com/taxigps 的另一个中文插件库。
(我记不清楚了，刚开始做的时候集合了前面几个大神的插件源)

**Comment by MV9KEz7nx6dx** [comment]
哈哈 感谢回复 已弃坑 kodi 在ios上不是太稳定
